"""
Django settings for GYMFlow project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

from django.core.management.commands.runserver import Command as runserver
from dotenv import dotenv_values, load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Cargar variables de entorno desde .env (si existe)
load_dotenv(BASE_DIR / ".env")
env = dotenv_values(BASE_DIR / ".env")


# Quick-start development settings - TODO: unsuitable for production
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-o^&2jtb!@ztx-(wjgyp!i8-!!(kk90!jp6xqtnu5j%ildyip9w"
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition
INSTALLED_APPS = [
    # Apps por defecto
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Nuestras Apps
    "corsheaders",  # https://github.com/adamchainz/django-cors-headers
    "users",  # Módulo de autenticación y gestión de usuarios
    "classes",  # Módulo de gestión de clases e inscripciones
    "payments",  # Módulo de gestion de cobros
    "attendance",  # Módulo de asistencia
    "reports",  # Módulo de reportes y métricas
    "notifications",  # Módulo de notificaciones
]

MIDDLEWARE = [
    # Middlewares por defecto
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    # Nuestros middlewares
    # https://github.com/adamchainz/django-cors-headers
    "corsheaders.middleware.CorsMiddleware",
]

ROOT_URLCONF = "GYMFlow.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "GYMFlow.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
#
# Configurar las variables de entorno para la base de datos.
# Para el desarrollo, utilizamos un servicio PostgreSQL dockerizado. Ver docker-compose.yml
# Si no se proporcionan las variables de entorno de Postgres en el archivo .env o en el entorno,
# se lanza una excepción.
if env.get("POSTGRES_DB"):
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": env.get("POSTGRES_DB", "gymflow"),
            "USER": env.get("POSTGRES_USER", "gymflow"),
            "PASSWORD": env.get("POSTGRES_PASSWORD", "gymflow"),
            "HOST": env.get("POSTGRES_HOST", "localhost"),
            "PORT": env.get("POSTGRES_PORT", "5432"),
        }
    }
else:
    raise Exception("No se proporcionaron las variables de entorno de Postgres en .env")


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/
LANGUAGE_CODE = "es-AR"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/
STATIC_URL = "/static/"
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# LOGIN
LOGIN_URL = "/users/login/"  # nombre de la URL de login
LOGIN_REDIRECT_URL = "dashboard"  # después de iniciar sesión, a dónde va
LOGOUT_REDIRECT_URL = "login"  # después de cerrar sesión


# Servidor
runserver.default_port = "8000"
