"""
Django settings for GYMFlow project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - TODO: unsuitable for production
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-o^&2jtb!@ztx-(wjgyp!i8-!!(kk90!jp6xqtnu5j%ildyip9w"
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition
INSTALLED_APPS = [
    # Apps por defecto
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Nuestras Apps
    "corsheaders",  # https://github.com/adamchainz/django-cors-headers
    "users",  # Módulo de autenticación y gestión de usuarios
    "classes",  # Módulo de gestión de clases e inscripciones
    "payments",  # Módulo de gestion de cobros
    "attendance",  # Módulo de asistencia
    "reports",  # Módulo de reportes y métricas
    "notifications",  # Módulo de notificaciones
]

MIDDLEWARE = [
    # Middlewares por defecto
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    # Nuestros middlewares
    # https://github.com/adamchainz/django-cors-headers
    "corsheaders.middleware.CorsMiddleware",
]

ROOT_URLCONF = "GYMFlow.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "GYMFlow.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
#
# PostgreSQL
# https://docs.djangoproject.com/en/6.0/ref/databases/#postgresql-notes
DATABASES = {
    # "default": {
    #     "ENGINE": "django.db.backends.postgresql",
    #     "OPTIONS": {},
    # }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/
LANGUAGE_CODE = "es-AR"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_URL = "static/"

# LOGIN
LOGIN_URL = '/users/login'         # nombre de la URL de login
#TODO: LOGIN_REDIRECT_URL = '/'    # después de iniciar sesión, a dónde va
#TODO: LOGOUT_REDIRECT_URL = '/'   # después de cerrar sesión
