"""
Django settings for GYMFlow project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

from django.core.management.commands.runserver import Command as runserver
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Cargar variables de entorno desde .env (si existe)
load_dotenv(BASE_DIR / ".env")

# Configuración de desarrollo
SECRET_KEY = os.environ["DJANGO_SECRET_KEY"]
DEBUG = os.environ.get("DJANGO_DEBUG", "True").lower() == "true"
ALLOWED_HOSTS = os.environ.get(
    "DJANGO_ALLOWED_HOSTS", "localhost 127.0.0.1 [::1]"
).split(" ")
PUBLIC_WEBHOOK_BASE_URL = os.environ.get("PUBLIC_WEBHOOK_BASE_URL", "").rstrip("/")
CSRF_TRUSTED_ORIGINS = [PUBLIC_WEBHOOK_BASE_URL] if PUBLIC_WEBHOOK_BASE_URL else []
MERCADO_PAGO_WEBHOOK_SECRET = os.environ.get("MERCADO_PAGO_WEBHOOK_SECRET", "")
if PUBLIC_WEBHOOK_BASE_URL.startswith("https://"):
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    USE_X_FORWARDED_HOST = True

# Application definition
INSTALLED_APPS = [
    # Apps por defecto
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Nuestras Apps
    "corsheaders",  # https://github.com/adamchainz/django-cors-headers
    "apps.users",  # Módulo de autenticación y gestión de usuarios
    "apps.classes",  # Módulo de gestión de clases e inscripciones
    "apps.payments",  # Módulo de gestion de cobros
    "apps.attendance",  # Módulo de asistencia
    "apps.reports",  # Módulo de reportes y métricas
    "apps.notifications",  # Módulo de notificaciones
    "django_q",  # Django Q2 para tareas en segundo plano
]

MIDDLEWARE = [
    # Middlewares por defecto
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "apps.users.middleware.TwoFactorMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    # Nuestros middlewares
    # https://github.com/adamchainz/django-cors-headers
    "corsheaders.middleware.CorsMiddleware",
]

ROOT_URLCONF = "GYMFlow.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "apps.payments.context_processors.cliente_creditos",
                "GYMFlow.context_processors.page_chrome",
            ],
        },
    },
]

WSGI_APPLICATION = "GYMFlow.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
POSTGRES_DB = os.environ.get("POSTGRES_DB")
if POSTGRES_DB:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": POSTGRES_DB,
            "USER": os.environ["POSTGRES_USER"],
            "PASSWORD": os.environ["POSTGRES_PASSWORD"],
            "HOST": os.environ.get("POSTGRES_HOST", "localhost"),
            "PORT": os.environ.get("POSTGRES_PORT", "5432"),
        }
    }
else:
    raise Exception("No se proporcionaron las variables de entorno de Postgres en .env")

# Django Q2 Configuration
Q_CLUSTER = {
    "name": "GYMFlow_Cluster",
    "workers": 4,
    "recycle": 500,
    "timeout": 60,
    "compress": True,
    "save_limit": 250,
    "queue_limit": 500,
    "label": "Django Q",
    "orm": "default",  # Usar la base de datos por defecto como broker
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "apps.users.validators.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "apps.users.validators.MinimumLengthValidator",
        "OPTIONS": {
            "min_length": 10,
        },
    },
    {
        "NAME": "apps.users.validators.CommonPasswordValidator",
    },
    {
        "NAME": "apps.users.validators.NumericPasswordValidator",
    },
    {
        "NAME": "apps.users.validators.LetterValidator",
    },
    {
        "NAME": "apps.users.validators.NumberValidator",
    },
    {
        "NAME": "apps.users.validators.SpecialCharacterValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/
LANGUAGE_CODE = "es-AR"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/
STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# LOGIN
LOGIN_URL = "/users/login/"  # nombre de la URL de login
LOGIN_REDIRECT_URL = "dashboard"  # después de iniciar sesión, a dónde va
LOGOUT_REDIRECT_URL = "login"  # después de cerrar sesión

AUTH_USER_MODEL = "users.User"

# Servidor
runserver.default_port = "8000"

# Email Configuration
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = os.environ.get("EMAIL_HOST", "localhost")
EMAIL_PORT = int(os.environ.get("EMAIL_PORT", 587))
EMAIL_USE_TLS = os.environ.get("EMAIL_USE_TLS", "True").lower() == "true"
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD", "")
DEFAULT_FROM_EMAIL = os.environ.get(
    "DEFAULT_FROM_EMAIL", "GYMFlow <noreply@gymflow.com>"
)

# Notification Configuration
NOTIFICATION_ADAPTERS = [
    "apps.notifications.adapters.email.EmailNotificationAdapter",
]
if DEBUG:
    NOTIFICATION_ADAPTERS.insert(
        0, "apps.notifications.adapters.email.FakeEmailNotificationAdapter"
    )

# Restricciones de horarios (clases de 60 min y que arrancan en :00)
GYM_RESTRICTED_SCHEDULE = True

# Precio por defecto para una clase (usado cuando no hay una tarifa por disciplina)
CLASE_DEFAULT_PRICE = float(os.environ.get("CLASE_DEFAULT_PRICE", "2500.0"))

# Horizonte de días que se muestra para fechas de clase suelta.
# Impacta qué ocurrencias futuras pueden seleccionarse en el flujo cliente.
VENTANA_OCURRENCIAS_CLASE_SUELTA_DIAS = int(
    os.environ.get("VENTANA_OCURRENCIAS_CLASE_SUELTA_DIAS", "21")
)

# Cantidad de días previos al inicio del período en que se habilita
# la preinscripción de abonados para el mes siguiente.
DIAS_PREINSCRIPCION_ABONADOS = int(os.environ.get("DIAS_PREINSCRIPCION_ABONADOS", "10"))

# Si está en True, no abonados pueden anotarse en pre-cola para clases
# del período siguiente antes de apertura_general (quedan en ESPERA).
# Si está en False, no abonados recién pueden inscribirse desde apertura_general.
# Es buena idea posibilitarlo. La lógica de prioridad para abonados se mantiene.
HABILITAR_PRECOLA_NO_ABONADOS = (
    os.environ.get("HABILITAR_PRECOLA_NO_ABONADOS", "true").lower() == "true"
)

# Día del mes (inclusive) hasta el que un abonado puede pagar su mensualidad
# sin perder la reserva. La conciliación empieza a considerar vencido desde el día siguiente.
DIA_LIMITE_PAGO_MENSUAL = int(os.environ.get("DIA_LIMITE_PAGO_MENSUAL", "10"))

# Activa la el proceso (Django Q) de la reconciliación de impagos mensuales.
# Esto es, cancela las inscripciones mensuales impagas vencidas del período vigente
# y promueve la lista de espera.
AUTO_RECONCILIACION_MENSUAL_ACTIVA = (
    os.environ.get("AUTO_RECONCILIACION_MENSUAL_ACTIVA", "true").lower() == "true"
)

# Hora diaria (HH:MM, 24h) en la que se ejecuta la conciliación automática.
AUTO_RECONCILIACION_MENSUAL_HORA = os.environ.get(
    "AUTO_RECONCILIACION_MENSUAL_HORA", "03:00"
)

# Horas mínimas de anticipación para cancelar una clase que forme parte de una inscripción mensual
CANCELACION_MENSUAL_HORAS_MIN = int(
    os.environ.get("CANCELACION_MENSUAL_HORAS_MIN", "48")
)
# Horas mínimas de anticipación para cancelar una clase suelta
CANCELACION_CLASE_SUELTA_HORAS_MIN = int(
    os.environ.get("CANCELACION_CLASE_SUELTA_HORAS_MIN", "24")
)

# Activar o desactivar la reconciliación de cupos de clases sueltas
AUTO_RECONCILIACION_SUELTA_ACTIVA = (
    os.environ.get("AUTO_RECONCILIACION_SUELTA_ACTIVA", "true").lower() == "true"
)

# Frecuencia en minutos para correr la tarea que limpia clases sueltas pendientes de pago
FRECUENCIA_RECONCILIACION_SUELTA_MINUTOS = int(
    os.environ.get("FRECUENCIA_RECONCILIACION_SUELTA_MINUTOS", "15")
)

# Tiempo de gracia (en minutos) antes de liberar una reserva de clase suelta impaga.
# Durante este período, el cupo de la clase SE ENCUENTRA RESERVADO para el usuario,
# quitándole lugar a otros posibles alumnos hasta que el pago se complete o el tiempo expire.
TIEMPO_GRACIA_PAGO_SUELTO_MINUTOS = int(
    os.environ.get("TIEMPO_GRACIA_PAGO_SUELTO_MINUTOS", "15")
)
