# Generated by Django 6.0.5 on 2026-06-07 22:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodoCobro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_inicio_periodo', models.DateField()),
                ('fecha_fin_periodo', models.DateField()),
                ('apertura_abonados', models.DateField()),
                ('apertura_general', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('metodo', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('MERCADOPAGO', 'MercadoPago'), ('CREDITO', 'Crédito')], max_length=20)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('COMPLETADO', 'Completado'), ('FALLIDO', 'Fallido'), ('REEMBOLSADO', 'Reembolsado')], default='PENDIENTE', max_length=20)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payments.periodocobro')),
            ],
        ),
        migrations.CreateModel(
            name='PagoInscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_aplicado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('inscripcion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='classes.inscripcion')),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='payments.pago')),
            ],
        ),
        migrations.CreateModel(
            name='Credito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('UTILIZADO', 'Utilizado')], default='DISPONIBLE', max_length=20)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.disciplina')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.periodocobro')),
            ],
        ),
        migrations.CreateModel(
            name='PrecioClase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.class')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.periodocobro')),
            ],
            options={
                'unique_together': {('clase', 'periodo')},
            },
        ),
    ]
