# Generated by Django 6.0.5 on 2026-05-28 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pago',
            name='modalidad_pago',
        ),
        migrations.AlterField(
            model_name='pago',
            name='metodo',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('MERCADOPAGO', 'MercadoPago'), ('CREDITO', 'Crédito')], max_length=20),
        ),
    ]
