# Generated by Django 6.0.5 on 2026-06-13 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_sync_is_staff_with_rol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='constancia_tutor',
        ),
    ]
