# Generated by Django 6.0.5 on 2026-05-13 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disciplina', models.CharField(max_length=100)),
                ('sala', models.CharField(max_length=100)),
                ('profesor', models.CharField(max_length=100)),
                ('inicio', models.DateTimeField()),
                ('duracion', models.DurationField()),
                ('cupo', models.IntegerField()),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('pausada', 'Pausada')], default='disponible', max_length=20)),
            ],
        ),
    ]
