# Generated by Django 6.0.5 on 2026-06-07 22:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcion',
            name='periodo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inscripciones', to='payments.periodocobro'),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inscripcionocurrencia',
            name='credito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ocurrencias_canceladas', to='payments.credito'),
        ),
        migrations.AddField(
            model_name='inscripcionocurrencia',
            name='inscripcion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocurrencias', to='classes.inscripcion'),
        ),
        migrations.AddField(
            model_name='class',
            name='sala',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='classes.sala'),
        ),
        migrations.AddField(
            model_name='sala',
            name='sede',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salas', to='classes.sede'),
        ),
        migrations.AlterUniqueTogether(
            name='teacher',
            unique_together={('nombre', 'apellido')},
        ),
        migrations.AddField(
            model_name='class',
            name='profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='classes.teacher'),
        ),
        migrations.AddConstraint(
            model_name='inscripcionocurrencia',
            constraint=models.UniqueConstraint(fields=('inscripcion', 'fecha_clase'), name='uniq_inscripcion_ocurrencia_fecha'),
        ),
        migrations.AlterUniqueTogether(
            name='sala',
            unique_together={('nombre', 'sede')},
        ),
    ]
