# Generated by Django 6.0.5 on 2026-06-17 02:19

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sala',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='sala',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('nombre'), models.F('sede'), name='uniq_sala_nombre_lower_sede'),
        ),
    ]
