# Generated by Django 6.0.5 on 2026-05-14 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_teacher_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.teacher'),
        ),
    ]
