# Generated by Django 6.0.5 on 2026-05-17 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0007_alter_class_to_foreignkey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='inicio',
        ),
        migrations.AddField(
            model_name='class',
            name='dia_semana',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], default=0),
        ),
        migrations.AddField(
            model_name='class',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
