# Generated by Django 6.0.5 on 2026-05-21 01:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0011_inscripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='disciplina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='classes.disciplina'),
        ),
    ]
