# Generated by Django 6.0.5 on 2026-05-28 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0012_alter_class_disciplina'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcion',
            name='periodo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inscripciones', to='payments.periodocobro'),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='tipo',
            field=models.CharField(choices=[('MENSUAL', 'Abonado Mensual'), ('CLASE_SUELTA', 'Clase Suelta (No Abonado)')], default='CLASE_SUELTA', max_length=20),
        ),
    ]
