# Generated by Django 6.0.5 on 2026-05-28 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0013_inscripcion_periodo_inscripcion_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripcion',
            name='tipo',
            field=models.CharField(choices=[('MENSUAL', 'Abonado (mensual)'), ('CLASE_SUELTA', 'No Abonado (clase suelta)')], default='CLASE_SUELTA', max_length=20),
        ),
    ]
