# Generated by Django 6.0.5 on 2026-05-31 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0017_inscripcion_ocurrencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripcionocurrencia',
            name='inscripcion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocurrencias', to='classes.inscripcion'),
        ),
    ]
